"""Updated Transaction with merchant. Ready to add filler data.

Revision ID: 04b2ca176d71
Revises: 130d06e4a951
Create Date: 2026-03-30 21:48:53.520848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b2ca176d71'
down_revision: Union[str, Sequence[str], None] = '130d06e4a951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('merchant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'merchants', ['merchant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_column('transactions', 'merchant_id')
    # ### end Alembic commands ###
