"""Budget Updated.

Revision ID: 0ddb4f28bc7a
Revises: a734fe437323
Create Date: 2026-04-26 12:27:03.187279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddb4f28bc7a'
down_revision: Union[str, Sequence[str], None] = 'a734fe437323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'budgets', 'categories', ['category_id'], ['id'])
    op.drop_column('budgets', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_column('budgets', 'category_id')
    # ### end Alembic commands ###
