"""Updated created at column.

Revision ID: 0f58fb50d948
Revises: 67808ca761c2
Create Date: 2026-04-24 12:37:55.028322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f58fb50d948'
down_revision: Union[str, Sequence[str], None] = '67808ca761c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('accounts', 'create_at')
    op.add_column('addresses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('addresses', 'create_at')
    op.add_column('budgets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('budgets', 'create_at')
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('categories', 'create_at')
    op.add_column('lenders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('lenders', 'create_at')
    op.add_column('merchants', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('merchants', 'create_at')
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('transactions', 'create_at')
    op.add_column('user_address', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('user_address', 'create_at')
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('users', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('users', 'created_at')
    op.add_column('user_address', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('user_address', 'created_at')
    op.add_column('transactions', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'created_at')
    op.add_column('merchants', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('merchants', 'created_at')
    op.add_column('lenders', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('lenders', 'created_at')
    op.add_column('categories', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('categories', 'created_at')
    op.add_column('budgets', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('budgets', 'created_at')
    op.add_column('addresses', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('addresses', 'created_at')
    op.add_column('accounts', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'created_at')
    # ### end Alembic commands ###
